site_name: Web 101
pages:
- [index.md, Home]
- [about.md, About]
- ['git/git_index.md', 'Git',"Introduction"]
- [git/git_video.md,'Git','video']
- [git/readme101.md,'Git','README']
- [git/github_page.md,'Git','Github Pages']
- [week/week1.md,'week','week1']
- [week/week2.md,'week','week2']
- [others/markdown.md,'others','Markdown']
- [others/sublime.md,'others','Sublime Text']
- [syllabus.md,'Syllabus']
- [html/html101.md,'HTML','Introduction']
- [html/development_tool.md,'HTML','Development Tools']

google_analytics: ['UA-60507351-1', 'web101']
# theme: readthedocs