site_name: Web 101
pages:
- [index.md, Home]
- [about.md, About]
- ['git/git_index.md', 'Git',"Introduction"]
- [git/git_video.md,'Git','video']
- [week/week1.md,'week','week1']
- [markdown.md,Markdown]
- [sublime.md,'Sublime Text']
- [syllabus.md,'Syllabus']




# theme: readthedocs