site_name: Web 101
pages:
- [index.md, Home]
- [about.md, About]
- ['git/git_index.md', 'Git',"Introduction"]
- [git/git_video.md,'Git','Videos']
- [git/readme101.md,'Git','README']
- [git/github_page.md,'Git','Github Pages']
- [week/week1.md,'week','week1']
- [week/week2.md,'week','week2']
- [week/week3.md,'week','week3']
- [week/week4.md,'week','week4']
- [week/week5.md,'week','week5']
- [week/week6.md,'week','week6']
- [week/week7.md,'week','week7']
- [week/week8.md,'week','week8']
- [week/week9.md,'week','week9']
- [week/week10.md,'week','week10']
- [others/markdown.md,'others','Markdown']
- [others/sublime.md,'others','Sublime Text']
- [others/install_ubuntu.md,'others','Install Ubuntu']
- [syllabus.md,'Syllabus']
- [html/html101.md,'HTML','Introduction']
- [html/development_tool.md,'HTML','Development Tools']
- [javascripts/introduction.md,'JavaScript','Introduction']
- [javascripts/jquery.md,'JavaScript','jQuery']
- [rails/rails101.md,'Rails','Introduction']
- [rails/videos.md,'Rails','Videos']
- [rails/ajax.md,'Rails','Ajax']
- [rails/user.md,'Rails','User']
- [db/videos.md,'DataBase','Videos']


google_analytics: ['UA-60507351-1', 'auto']
# theme: readthedocs
